<a href="https://colab.research.google.com/github/DarrenHsien/ML2021/blob/main/2_Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Tutorial**


In [15]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [16]:
# randn 隨機張量
x = torch.randn(4,5) # row, col
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[-1.3126, -0.2727, -0.6206,  2.3706,  0.2451],
        [ 0.7358, -2.0613,  0.9062,  0.7727,  0.9801],
        [ 1.2666,  1.4866, -1.2893, -0.6010, -0.1009],
        [ 0.2585,  0.7780, -0.9084,  1.5613,  0.4325]])
tensor([[-2.4785, -2.1946,  0.6123, -2.1224, -0.9403],
        [-0.9374,  1.5015,  0.1297, -0.0369,  0.8082],
        [-0.2638,  0.3217, -0.4958,  1.5805,  0.0282],
        [-0.6328, -2.3852, -0.5614, -1.9175,  0.4790]])
tensor([[ 0.7331,  0.2501, -1.9612, -0.3884,  0.2488],
        [ 0.9295, -0.1528,  0.4623,  1.0377,  1.0720],
        [ 0.0153, -0.1295,  0.3660, -0.0730,  0.0490],
        [ 0.8303, -0.1972, -0.9561,  0.3640,  0.5210]])


In [31]:
# list轉張量
a = torch.tensor(([1,1], [2,3]))
a[0]
m, idx = torch.max(a,dim=0)
print(m)
print(idx)
m, idx = torch.max(a,dim=1)
print(m)
print(idx)

tensor([2, 3])
tensor([1, 1])
tensor([1, 3])
tensor([0, 1])


In [32]:
# zeros
torch.zeros([2,3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
# ones
torch.ones([1,2,5])

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [38]:
# Squeeze : 排除指定維度當該維度向量數目為1
a = torch.zeros([1,2,3])
a.shape
a = a.squeeze(0)
print(a.shape)
print(a)

a = torch.zeros([2,2,3])
print(a.shape)
a = a.squeeze(0)
print(a.shape)
print(a)

torch.Size([2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [39]:
# Unsqueeze : 擴增一個新的維度向量數目為1
a = torch.zeros([2,3])
a.shape
a = a.unsqueeze(1)
print(a.shape)
print(a)

torch.Size([2, 1, 3])
tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])


In [42]:
# transpose : 指定兩維度對調
a = torch.tensor(([1,1], [2,3]))
print(a)
a = a.transpose(0,1)
print(a)

tensor([[1, 1],
        [2, 3]])
tensor([[1, 2],
        [1, 3]])


In [45]:
# cat : 在多個張量都為N維，其中N-1維張量大小都相同時，可合併指定唯一不同維度
a = torch.zeros([2,1,3])
b = torch.zeros([2,2,3])
c = torch.zeros([2,5,3])
# torch.cat([a, b, c], dim=2) # 會報錯
torch.cat([a, b, c], dim=1).shape

torch.Size([2, 8, 3])

In [52]:
# Addition
a = torch.tensor(([1,1], [1,1]))
b = torch.tensor(([1,2], [3,4]))
print(a+b)
# Subtraction
print(a-b)
# Power
print(a.pow(2))
# Summation
print(a.sum())
# Mean
a = a.type(torch.DoubleTensor)
print(a.dtype)
print(a.mean())

tensor([[2, 3],
        [4, 5]])
tensor([[ 0, -1],
        [-2, -3]])
tensor([[1, 1],
        [1, 1]])
tensor(4)
torch.float64
tensor(1., dtype=torch.float64)


In [17]:
 # max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(2.3706)


In [18]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0) # 以第0 dim進行計算最大值
print(m)
print(idx)

tensor([1.2666, 1.4866, 0.9062, 2.3706, 0.9801])
tensor([2, 2, 1, 0, 1])


In [19]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([1.2666, 1.4866, 0.9062, 2.3706, 0.9801])
tensor([2, 2, 1, 0, 1])


In [20]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)
print(m.size())

tensor([1.2666, 1.4866, 0.9062, 2.3706, 0.9801])
tensor([2, 2, 1, 0, 1])
torch.Size([5])


In [21]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True) # keepdim 維持原本矩陣維度
print(m)
print(idx)
print(m.size())

tensor([[1.2666, 1.4866, 0.9062, 2.3706, 0.9801]])
tensor([[2, 2, 1, 0, 1]])
torch.Size([1, 5])


In [22]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([1.2666, 1.4866, 0.9062, 2.3706, 0.9801])
tensor([2, 2, 1, 0, 1])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: An output with one or more elements was resized since it had shape [1, 1, 5], which does not match the required output shape [1, 5].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:23.)
  This is separate from the ipykernel package so we can avoid doing imports until


In [23]:
# 2-6
print(m)
p = (m,idx)
torch.max(x,0,False,p)
print(p[0])
print(p[1])

tensor([1.2666, 1.4866, 0.9062, 2.3706, 0.9801])


TypeError: ignored

In [24]:
# 2-7
m, idx = torch.max(x,True)

TypeError: ignored

In [ ]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)

**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [ ]:
import torch

In [ ]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)

In [ ]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

In [ ]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y= torch.randn(5,4)
z = x + y

In [ ]:
# 2. mismatched dimensions error (fixed)
y= y.transpose(0,1)
z = x + y
print(z.shape)

In [ ]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


In [ ]:
# 3. cuda out of memory error (fixed)
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)

In [ ]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels

In [ ]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [ ]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [ ]:
for datapoint in dataset:
  print(datapoint)

When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array. 



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [ ]:
import torch
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [ ]:
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)