<a href="https://colab.research.google.com/github/DarrenHsien/ML2021/blob/main/2_Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Tutorial**


In [2]:
import torch

**1. Pytorch Documentation Explanation with torch basic function**



In [3]:
# randn 隨機張量
x = torch.randn(4,5) # row, col
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[-0.6320, -0.7935,  0.0535, -0.1462, -1.5597],
        [ 0.1527, -0.1494, -0.0465,  1.2658,  1.3374],
        [ 0.8045, -0.2050, -1.2887, -2.3946,  0.8937],
        [-1.1780,  1.1830, -0.8668, -0.0566, -0.1693]])
tensor([[ 0.2449,  0.1273, -1.7816,  0.2638,  0.4155],
        [-0.5817,  0.4840, -0.5576, -1.7366, -0.9740],
        [-0.1635, -0.4571, -0.3984,  0.3856,  0.8864],
        [-0.4042,  0.4908, -0.5008,  0.4353,  0.2001]])
tensor([[-0.1010, -0.4662, -0.9895, -0.1360, -0.0314],
        [ 1.0055, -0.1718, -0.2971, -0.7576, -0.4528],
        [ 0.8602,  0.7506,  1.0831, -0.4601,  1.4362],
        [ 0.8652,  0.3114, -0.7346,  0.4274,  0.1814]])


In [4]:
# list轉張量
a = torch.tensor(([1,1], [2,3]))
a[0]
m, idx = torch.max(a,dim=0)
print(m)
print(idx)
m, idx = torch.max(a,dim=1)
print(m)
print(idx)

tensor([2, 3])
tensor([1, 1])
tensor([1, 3])
tensor([0, 1])


In [5]:
# zeros
torch.zeros([2,3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# ones
torch.ones([1,2,5])

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [7]:
# Squeeze : 排除指定維度當該維度向量數目為1
a = torch.zeros([1,2,3])
a.shape
a = a.squeeze(0)
print(a.shape)
print(a)

a = torch.zeros([2,2,3])
print(a.shape)
a = a.squeeze(0)
print(a.shape)
print(a)

torch.Size([2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [8]:
# Unsqueeze : 擴增一個新的維度向量數目為1
a = torch.zeros([2,3])
a.shape
a = a.unsqueeze(1)
print(a.shape)
print(a)

torch.Size([2, 1, 3])
tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])


In [9]:
# transpose : 指定兩維度對調
a = torch.tensor(([1,1], [2,3]))
print(a)
a = a.transpose(0,1)
print(a)

tensor([[1, 1],
        [2, 3]])
tensor([[1, 2],
        [1, 3]])


In [10]:
# cat : 在多個張量都為N維，其中N-1維張量大小都相同時，可合併指定唯一不同維度
a = torch.zeros([2,1,3])
b = torch.zeros([2,2,3])
c = torch.zeros([2,5,3])
# torch.cat([a, b, c], dim=2) # 會報錯
torch.cat([a, b, c], dim=1).shape

torch.Size([2, 8, 3])

In [11]:
# Addition
a = torch.tensor(([1,1], [1,1]))
b = torch.tensor(([1,2], [3,4]))
print(a+b)
# Subtraction
print(a-b)
# Power
print(a.pow(2))
# Summation
print(a.sum())
# Mean
a = a.type(torch.DoubleTensor)
print(a.dtype)
print(a.mean())

tensor([[2, 3],
        [4, 5]])
tensor([[ 0, -1],
        [-2, -3]])
tensor([[1, 1],
        [1, 1]])
tensor(4)
torch.float64
tensor(1., dtype=torch.float64)


In [46]:
# item 將張量轉為純量

a = torch.tensor([2])
print(a)
print(a.item())

tensor([2])
2


In [12]:
# check gpu exist
print(torch.cuda.is_available())
# Tensor to CPU or GPU
a = torch.tensor(([1,1], [1,1]))
b = torch.tensor(([1,1], [1,1]))
print(a.to('cuda'))
print(b.to('cpu'))

True
tensor([[1, 1],
        [1, 1]], device='cuda:0')
tensor([[1, 1],
        [1, 1]])


In [13]:
 # 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(1.3374)


In [14]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0) # 以第0 dim進行計算最大值
print(m)
print(idx)

tensor([0.8045, 1.1830, 0.0535, 1.2658, 1.3374])
tensor([2, 3, 0, 1, 1])


In [15]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([0.8045, 1.1830, 0.0535, 1.2658, 1.3374])
tensor([2, 3, 0, 1, 1])


In [42]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)
print(m.size())

tensor([1., 1.], grad_fn=<MaxBackward0>)
tensor([0, 1])
torch.Size([2])


In [17]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True) # keepdim 維持原本矩陣維度
print(m)
print(idx)
print(m.size())

tensor([[0.8045, 1.1830, 0.0535, 1.2658, 1.3374]])
tensor([[2, 3, 0, 1, 1]])
torch.Size([1, 5])


In [18]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([0.8045, 1.1830, 0.0535, 1.2658, 1.3374])
tensor([2, 3, 0, 1, 1])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: An output with one or more elements was resized since it had shape [1, 1, 5], which does not match the required output shape [1, 5].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:23.)
  This is separate from the ipykernel package so we can avoid doing imports until


In [19]:
# How to caculate gradient
"""
x = [[1,0], [-1,1]]
f(x) = SUMiSUMJ X^2
partial f(x) with x = 2XiXj
partial f(x) with x = [[2,0], [-2,2]]
"""

# x = torch.tensor([[1,0],[-1,1]], requires_grad=True) 導入gradien計算需為浮點型態
x = torch.tensor([[1.,0.],[-1.,1.]], requires_grad=True)
f = x.pow(2).sum()
print(f)
f.backward()
print(x.grad)


tensor(3., grad_fn=<SumBackward0>)
tensor([[ 2.,  0.],
        [-2.,  2.]])


**2.Dataset & Dataloader**

In [ ]:
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):
  # Read data & preprecess
  def __init__(self, file):
    # self.data = read
    pass
  # Return one sample at a time
  def __getitem__(self, index):
    return self.data[index]
  # Return the size of the size
  def __len__(self):
    return len(self.data)

dataset = MyDataset(file)

# set dataset into dataloader
# dataloader will use __getitem__ function to get batch of data
dataloader = Dataloader(dataset, batch_size, shuffle=True)


**3.torch.nn**

In [26]:
# Linear Layer(Fully-connected Layer)
"""
input X1-32 => W32X64 * X + b = Y
"""
W = torch.nn.Linear(32,64)
print(W.weight.shape)
print(W.bias.shape)

torch.Size([64, 32])
torch.Size([64])


In [36]:
# Activation Function
torch.nn.Sigmoid()
torch.nn.ReLU(W)

ReLU(
  inplace=True
  (inplace): Linear(in_features=32, out_features=64, bias=True)
)

In [37]:
# Loss Functions
# MSE
torch.nn.MSELoss()
# Cross Entropy
torch.nn.CrossEntropyLoss()

CrossEntropyLoss()

In [38]:
# Build own neural network
import torch.nn as nn
# nn.Module : 支援建模class
# nn.Sequential : 串接網絡層 
class MyModel(nn.Module):
  # initialize model & define layers
  def __init__(self):
    super(MyModel, self).__init__()
    self.net = nn.Sequential(
        nn.Linear(10,32),
        nn.Sigmoid(),
        nn.Linear(32,1)
    )
  
  # 計算資料進入model後的output
  def forward(self, x):
    return self.net(x)


In [39]:
# Optimization => compute gradient descent
# SGD(Stochastic Gradient Descent)
# torch.optim.SGD(params<model.parameters()>, lr, momentum = 0)


**4. Model Training & Validatin & Testing Concept**

In [ ]:
from torch.optim import optimizer
# 1.Training tool preprocess
"""
dataset = MyDataset(file) # 導入訓練文件資料製作成dataset
tr_set = DataLoader(dataset, batch_size=16, shuffle=True) # 建立dataset讀取器
model = MyModel().to(device='gpu') # 將模型參數導入顯卡設備
criterion = nn.MSELoss() # 製作用來計算預測與gt的LossFunction
optimizer = torch.optim.SGD(model.parameters(), momentum=0.9, lr=0.1) # 用來訓練迭代中計算更新梯度的優化器
"""

# 2. Training run
"""
for epoch in range(n_epochs): # for loop 設定訓練步數
  model.train() # 設定模型為train mode才可以更新內部參數
  
  for x, y in tr_set: # 每個epoch須完整訓練更新所有資料集
    optimizer.zero_grad() # 清空上一次的gradient數值 & 展現Gradient accumulation
    x, y = x.to(device), y.to(device) # 將資料導入顯卡設備
    pred = model(x) # 導入資料計算預測結果 => foward probagation
    loss = criterion(pred, y) # 計算pred與gt loss
    loss.backward() # 計算grdient => backprobagation
    optimizer.step() # 使用optimizer更新model.params

"""

# 3. Validation run
"""
model.eval() # 設定模型為eval mode才不會更新內部參數
total_loss = 0
for x, y in dv_det:
  x, y = x.to(device), y.to(device) # 將資料導入顯卡設備
  with torch.no_grad(): # 在驗證時，控制模型不需要track gradient
    pred = model(x) # 導入資料計算預測結果 => foward probagation
    loss = criterion(pred, y) # 計算pred與gt loss
  total_loss += loss.cpu().item()*len(x) # 將loss轉回cpu處理並從張量轉為純量後乘以所有資料量等於這個batch的loss再加總
  avg_loss = total_loss / len(dv_set.dataset)
"""

# 4. Testing run
"""
model.eval() # 設定模型為eval mode才不會更新內部參數
preds = []
for x in tt_det:
  x = x.to(device) # 將資料導入顯卡設備
  with torch.no_grad(): # 在驗證時，控制模型不需要track gradient
    pred = model(x) # 導入資料計算預測結果 => foward probagation
    preds.append(pred.cpu())
"""

# 5. Save Model
"""
torch.save(model.state_dict(), path)
"""
# 6. Load Model
"""
ckpt = torch.load(path)
model.load_state_dict(ckpt)
"""
